//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyCommunication.CompanyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronymicField;
        
        private bool TraineeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompanyCommunication.CompanyService.ArrayOfString CurDepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceOfWorkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Patronymic {
            get {
                return this.PatronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronymicField, value) != true)) {
                    this.PatronymicField = value;
                    this.RaisePropertyChanged("Patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Trainee {
            get {
                return this.TraineeField;
            }
            set {
                if ((this.TraineeField.Equals(value) != true)) {
                    this.TraineeField = value;
                    this.RaisePropertyChanged("Trainee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CompanyCommunication.CompanyService.ArrayOfString CurDep {
            get {
                return this.CurDepField;
            }
            set {
                if ((object.ReferenceEquals(this.CurDepField, value) != true)) {
                    this.CurDepField = value;
                    this.RaisePropertyChanged("CurDep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PlaceOfWork {
            get {
                return this.PlaceOfWorkField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceOfWorkField, value) != true)) {
                    this.PlaceOfWorkField = value;
                    this.RaisePropertyChanged("PlaceOfWork");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Dep {
            get {
                return this.DepField;
            }
            set {
                if ((object.ReferenceEquals(this.DepField, value) != true)) {
                    this.DepField = value;
                    this.RaisePropertyChanged("Dep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.CompanyServiceSoap")]
    public interface CompanyServiceSoap {
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        CompanyCommunication.CompanyService.AddEmployeeResponse AddEmployee(CompanyCommunication.CompanyService.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.AddEmployeeResponse> AddEmployeeAsync(CompanyCommunication.CompanyService.AddEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name department from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDepartment", ReplyAction="*")]
        CompanyCommunication.CompanyService.AddDepartmentResponse AddDepartment(CompanyCommunication.CompanyService.AddDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.AddDepartmentResponse> AddDepartmentAsync(CompanyCommunication.CompanyService.AddDepartmentRequest request);
        
        // CODEGEN: Generating message contract since element name LoadEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadEmployees", ReplyAction="*")]
        CompanyCommunication.CompanyService.LoadEmployeesResponse LoadEmployees(CompanyCommunication.CompanyService.LoadEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.LoadEmployeesResponse> LoadEmployeesAsync(CompanyCommunication.CompanyService.LoadEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name LoadDepartmentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDepartments", ReplyAction="*")]
        CompanyCommunication.CompanyService.LoadDepartmentsResponse LoadDepartments(CompanyCommunication.CompanyService.LoadDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.LoadDepartmentsResponse> LoadDepartmentsAsync(CompanyCommunication.CompanyService.LoadDepartmentsRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        CompanyCommunication.CompanyService.RemoveResponse Remove(CompanyCommunication.CompanyService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.RemoveResponse> RemoveAsync(CompanyCommunication.CompanyService.RemoveRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        CompanyCommunication.CompanyService.UpdateResponse Update(CompanyCommunication.CompanyService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.UpdateResponse> UpdateAsync(CompanyCommunication.CompanyService.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployee", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.AddEmployeeRequestBody Body;
        
        public AddEmployeeRequest() {
        }
        
        public AddEmployeeRequest(CompanyCommunication.CompanyService.AddEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompanyCommunication.CompanyService.Employee employee;
        
        public AddEmployeeRequestBody() {
        }
        
        public AddEmployeeRequestBody(CompanyCommunication.CompanyService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.AddEmployeeResponseBody Body;
        
        public AddEmployeeResponse() {
        }
        
        public AddEmployeeResponse(CompanyCommunication.CompanyService.AddEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddEmployeeResult;
        
        public AddEmployeeResponseBody() {
        }
        
        public AddEmployeeResponseBody(int AddEmployeeResult) {
            this.AddEmployeeResult = AddEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDepartment", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.AddDepartmentRequestBody Body;
        
        public AddDepartmentRequest() {
        }
        
        public AddDepartmentRequest(CompanyCommunication.CompanyService.AddDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompanyCommunication.CompanyService.Department department;
        
        public AddDepartmentRequestBody() {
        }
        
        public AddDepartmentRequestBody(CompanyCommunication.CompanyService.Department department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.AddDepartmentResponseBody Body;
        
        public AddDepartmentResponse() {
        }
        
        public AddDepartmentResponse(CompanyCommunication.CompanyService.AddDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDepartmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddDepartmentResult;
        
        public AddDepartmentResponseBody() {
        }
        
        public AddDepartmentResponseBody(int AddDepartmentResult) {
            this.AddDepartmentResult = AddDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEmployees", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.LoadEmployeesRequestBody Body;
        
        public LoadEmployeesRequest() {
        }
        
        public LoadEmployeesRequest(CompanyCommunication.CompanyService.LoadEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadEmployeesRequestBody {
        
        public LoadEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.LoadEmployeesResponseBody Body;
        
        public LoadEmployeesResponse() {
        }
        
        public LoadEmployeesResponse(CompanyCommunication.CompanyService.LoadEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompanyCommunication.CompanyService.Employee[] LoadEmployeesResult;
        
        public LoadEmployeesResponseBody() {
        }
        
        public LoadEmployeesResponseBody(CompanyCommunication.CompanyService.Employee[] LoadEmployeesResult) {
            this.LoadEmployeesResult = LoadEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDepartments", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.LoadDepartmentsRequestBody Body;
        
        public LoadDepartmentsRequest() {
        }
        
        public LoadDepartmentsRequest(CompanyCommunication.CompanyService.LoadDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadDepartmentsRequestBody {
        
        public LoadDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDepartmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.LoadDepartmentsResponseBody Body;
        
        public LoadDepartmentsResponse() {
        }
        
        public LoadDepartmentsResponse(CompanyCommunication.CompanyService.LoadDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompanyCommunication.CompanyService.Department[] LoadDepartmentsResult;
        
        public LoadDepartmentsResponseBody() {
        }
        
        public LoadDepartmentsResponseBody(CompanyCommunication.CompanyService.Department[] LoadDepartmentsResult) {
            this.LoadDepartmentsResult = LoadDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(CompanyCommunication.CompanyService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompanyCommunication.CompanyService.Employee employee;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(CompanyCommunication.CompanyService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(CompanyCommunication.CompanyService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(int RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(CompanyCommunication.CompanyService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CompanyCommunication.CompanyService.Employee employee;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(CompanyCommunication.CompanyService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CompanyCommunication.CompanyService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(CompanyCommunication.CompanyService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompanyServiceSoapChannel : CompanyCommunication.CompanyService.CompanyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyServiceSoapClient : System.ServiceModel.ClientBase<CompanyCommunication.CompanyService.CompanyServiceSoap>, CompanyCommunication.CompanyService.CompanyServiceSoap {
        
        public CompanyServiceSoapClient() {
        }
        
        public CompanyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyCommunication.CompanyService.AddEmployeeResponse CompanyCommunication.CompanyService.CompanyServiceSoap.AddEmployee(CompanyCommunication.CompanyService.AddEmployeeRequest request) {
            return base.Channel.AddEmployee(request);
        }
        
        public int AddEmployee(CompanyCommunication.CompanyService.Employee employee) {
            CompanyCommunication.CompanyService.AddEmployeeRequest inValue = new CompanyCommunication.CompanyService.AddEmployeeRequest();
            inValue.Body = new CompanyCommunication.CompanyService.AddEmployeeRequestBody();
            inValue.Body.employee = employee;
            CompanyCommunication.CompanyService.AddEmployeeResponse retVal = ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).AddEmployee(inValue);
            return retVal.Body.AddEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.AddEmployeeResponse> CompanyCommunication.CompanyService.CompanyServiceSoap.AddEmployeeAsync(CompanyCommunication.CompanyService.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyCommunication.CompanyService.AddEmployeeResponse> AddEmployeeAsync(CompanyCommunication.CompanyService.Employee employee) {
            CompanyCommunication.CompanyService.AddEmployeeRequest inValue = new CompanyCommunication.CompanyService.AddEmployeeRequest();
            inValue.Body = new CompanyCommunication.CompanyService.AddEmployeeRequestBody();
            inValue.Body.employee = employee;
            return ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).AddEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyCommunication.CompanyService.AddDepartmentResponse CompanyCommunication.CompanyService.CompanyServiceSoap.AddDepartment(CompanyCommunication.CompanyService.AddDepartmentRequest request) {
            return base.Channel.AddDepartment(request);
        }
        
        public int AddDepartment(CompanyCommunication.CompanyService.Department department) {
            CompanyCommunication.CompanyService.AddDepartmentRequest inValue = new CompanyCommunication.CompanyService.AddDepartmentRequest();
            inValue.Body = new CompanyCommunication.CompanyService.AddDepartmentRequestBody();
            inValue.Body.department = department;
            CompanyCommunication.CompanyService.AddDepartmentResponse retVal = ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).AddDepartment(inValue);
            return retVal.Body.AddDepartmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.AddDepartmentResponse> CompanyCommunication.CompanyService.CompanyServiceSoap.AddDepartmentAsync(CompanyCommunication.CompanyService.AddDepartmentRequest request) {
            return base.Channel.AddDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyCommunication.CompanyService.AddDepartmentResponse> AddDepartmentAsync(CompanyCommunication.CompanyService.Department department) {
            CompanyCommunication.CompanyService.AddDepartmentRequest inValue = new CompanyCommunication.CompanyService.AddDepartmentRequest();
            inValue.Body = new CompanyCommunication.CompanyService.AddDepartmentRequestBody();
            inValue.Body.department = department;
            return ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).AddDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyCommunication.CompanyService.LoadEmployeesResponse CompanyCommunication.CompanyService.CompanyServiceSoap.LoadEmployees(CompanyCommunication.CompanyService.LoadEmployeesRequest request) {
            return base.Channel.LoadEmployees(request);
        }
        
        public CompanyCommunication.CompanyService.Employee[] LoadEmployees() {
            CompanyCommunication.CompanyService.LoadEmployeesRequest inValue = new CompanyCommunication.CompanyService.LoadEmployeesRequest();
            inValue.Body = new CompanyCommunication.CompanyService.LoadEmployeesRequestBody();
            CompanyCommunication.CompanyService.LoadEmployeesResponse retVal = ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).LoadEmployees(inValue);
            return retVal.Body.LoadEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.LoadEmployeesResponse> CompanyCommunication.CompanyService.CompanyServiceSoap.LoadEmployeesAsync(CompanyCommunication.CompanyService.LoadEmployeesRequest request) {
            return base.Channel.LoadEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyCommunication.CompanyService.LoadEmployeesResponse> LoadEmployeesAsync() {
            CompanyCommunication.CompanyService.LoadEmployeesRequest inValue = new CompanyCommunication.CompanyService.LoadEmployeesRequest();
            inValue.Body = new CompanyCommunication.CompanyService.LoadEmployeesRequestBody();
            return ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).LoadEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyCommunication.CompanyService.LoadDepartmentsResponse CompanyCommunication.CompanyService.CompanyServiceSoap.LoadDepartments(CompanyCommunication.CompanyService.LoadDepartmentsRequest request) {
            return base.Channel.LoadDepartments(request);
        }
        
        public CompanyCommunication.CompanyService.Department[] LoadDepartments() {
            CompanyCommunication.CompanyService.LoadDepartmentsRequest inValue = new CompanyCommunication.CompanyService.LoadDepartmentsRequest();
            inValue.Body = new CompanyCommunication.CompanyService.LoadDepartmentsRequestBody();
            CompanyCommunication.CompanyService.LoadDepartmentsResponse retVal = ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).LoadDepartments(inValue);
            return retVal.Body.LoadDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.LoadDepartmentsResponse> CompanyCommunication.CompanyService.CompanyServiceSoap.LoadDepartmentsAsync(CompanyCommunication.CompanyService.LoadDepartmentsRequest request) {
            return base.Channel.LoadDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyCommunication.CompanyService.LoadDepartmentsResponse> LoadDepartmentsAsync() {
            CompanyCommunication.CompanyService.LoadDepartmentsRequest inValue = new CompanyCommunication.CompanyService.LoadDepartmentsRequest();
            inValue.Body = new CompanyCommunication.CompanyService.LoadDepartmentsRequestBody();
            return ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).LoadDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyCommunication.CompanyService.RemoveResponse CompanyCommunication.CompanyService.CompanyServiceSoap.Remove(CompanyCommunication.CompanyService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(CompanyCommunication.CompanyService.Employee employee) {
            CompanyCommunication.CompanyService.RemoveRequest inValue = new CompanyCommunication.CompanyService.RemoveRequest();
            inValue.Body = new CompanyCommunication.CompanyService.RemoveRequestBody();
            inValue.Body.employee = employee;
            CompanyCommunication.CompanyService.RemoveResponse retVal = ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.RemoveResponse> CompanyCommunication.CompanyService.CompanyServiceSoap.RemoveAsync(CompanyCommunication.CompanyService.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyCommunication.CompanyService.RemoveResponse> RemoveAsync(CompanyCommunication.CompanyService.Employee employee) {
            CompanyCommunication.CompanyService.RemoveRequest inValue = new CompanyCommunication.CompanyService.RemoveRequest();
            inValue.Body = new CompanyCommunication.CompanyService.RemoveRequestBody();
            inValue.Body.employee = employee;
            return ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyCommunication.CompanyService.UpdateResponse CompanyCommunication.CompanyService.CompanyServiceSoap.Update(CompanyCommunication.CompanyService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(CompanyCommunication.CompanyService.Employee employee) {
            CompanyCommunication.CompanyService.UpdateRequest inValue = new CompanyCommunication.CompanyService.UpdateRequest();
            inValue.Body = new CompanyCommunication.CompanyService.UpdateRequestBody();
            inValue.Body.employee = employee;
            CompanyCommunication.CompanyService.UpdateResponse retVal = ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyCommunication.CompanyService.UpdateResponse> CompanyCommunication.CompanyService.CompanyServiceSoap.UpdateAsync(CompanyCommunication.CompanyService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyCommunication.CompanyService.UpdateResponse> UpdateAsync(CompanyCommunication.CompanyService.Employee employee) {
            CompanyCommunication.CompanyService.UpdateRequest inValue = new CompanyCommunication.CompanyService.UpdateRequest();
            inValue.Body = new CompanyCommunication.CompanyService.UpdateRequestBody();
            inValue.Body.employee = employee;
            return ((CompanyCommunication.CompanyService.CompanyServiceSoap)(this)).UpdateAsync(inValue);
        }
    }
}
